name: job_task
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  get: ^4.6.5
  get_it: ^7.2.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true


  assets:
  - assets/fonts/
  - assets/images/
  - assets/json/
    
fonts:   
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Light.ttf